# -*- coding: utf-8 -*-
"""DatosnoOriginales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6axZwZVIxCnF4G0q4hINdLeCgv59lWh
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import matplotlib.pyplot as plt

archivo = "datos_sinteticos_circuito_25C.csv"

datos = np.loadtxt(archivo, delimiter=",", skiprows=6)

VA = datos[:, 0] / 1000.0
VB = datos[:, 1] / 1000.0

fs = 50e6
t = np.arange(len(VA)) / fs

Vout = VA - VB

Vout_max = np.max(Vout)
Vout_min = np.min(Vout)
Vout_pp = Vout_max - Vout_min
Vout_pico = Vout_pp / 2

Vin = 2 * VA

idx_in = np.argmax(Vin)
idx_out = np.argmax(Vout)

delta_t = t[idx_out] - t[idx_in]

f = 10000
fase = delta_t * f * 360

print("RESULTADOS")
print(f"VA Vpp = {np.ptp(VA):.4f} V")
print(f"VB Vpp = {np.ptp(VB):.4f} V")
print(f"Vout Vpp = {Vout_pp:.4f} V")
print(f"Vout pico = {Vout_pico:.4f} V")
print(f"Delta t = {delta_t*1e6:.3f} us")
print(f"Fase = {fase:.2f} grados")

plt.figure(figsize=(10,5))
plt.plot(t*1e6, VA, label="CH1 - Nodo A")
plt.plot(t*1e6, VB, label="CH2 - Nodo B")
plt.plot(t*1e6, Vout, label="Vout = VA - VB")

plt.xlabel("Tiempo (us)")
plt.ylabel("Voltaje (V)")
plt.title("Puente de Wheatstone - Datos experimentales")
plt.grid()
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1. CONFIGURACIÓN
# ============================================================

archivo = "DEFAULT1.csv"

# Datos del laboratorio
T_celsius = 25.0
f = 10000.0                  # 10 kHz
fs = 50e6                    # 50 MSa/s del CSV

R1 = 10000.0
R2 = 10000.0
R3 = 10000.0

# Dos resistencias de 20 ohm en paralelo
R_a = 20.0
R_b = 20.0
R_cable = (R_a * R_b) / (R_a + R_b)

L = 14.7e-6                  # 14.7 uH
C = 4.7e-9                   # 4.7 nF

# Parámetros del NTC
R0 = 10000.0
Beta = 3950.0
T0 = 25.0 + 273.15

# ============================================================
# 2. LEER CSV REAL DEL OSCILOSCOPIO
# ============================================================

# El archivo tiene 6 líneas de encabezado
datos = np.loadtxt(
    archivo,
    delimiter=",",
    skiprows=6
)

# El CSV guarda los voltajes en mV
VA = datos[:, 0] / 1000.0
VB = datos[:, 1] / 1000.0

# Vector de tiempo
t = np.arange(len(VA)) / fs

# ============================================================
# 3. DATOS EXPERIMENTALES ORIGINALES
# ============================================================

# El osciloscopio estaba conectado:
# CH1 = Nodo A
# CH2 = Nodo B

Vout_exp = VA - VB

VA_pp = np.ptp(VA)
VB_pp = np.ptp(VB)

Vout_pp_exp = np.ptp(Vout_exp)
Vout_pico_exp = Vout_pp_exp / 2.0

# Como R1 = R2 = 10k:
# VA = Vin/2
Vin_pp_estimado = 2.0 * VA_pp
Vin_pico_estimado = Vin_pp_estimado / 2.0

# ============================================================
# 4. NORMALIZACIÓN
# ============================================================

# Quitamos el offset antes de normalizar
VA_centrada = VA - np.mean(VA)
VB_centrada = VB - np.mean(VB)

# Normalización solo para comparar forma/fase.
# NO modifica los datos experimentales originales.
VA_norm = VA_centrada / np.max(np.abs(VA_centrada))
VB_norm = VB_centrada / np.max(np.abs(VB_centrada))

# ============================================================
# 5. CALCULAR DESFASE ENTRE CH1 Y CH2
#    usando correlación cruzada
# ============================================================

corr = np.correlate(
    VA_norm,
    VB_norm,
    mode="full"
)

lag = np.argmax(corr) - (len(VA_norm) - 1)

delta_t_AB = lag / fs

fase_AB = delta_t_AB * f * 360.0

# Llevar la fase al rango -180° a +180°
fase_AB = (fase_AB + 180) % 360 - 180

# ============================================================
# 6. MODELO TEÓRICO DEL NTC
# ============================================================

T_kelvin = T_celsius + 273.15

R_ntc = R0 * np.exp(
    Beta * (
        1.0 / T_kelvin
        - 1.0 / T0
    )
)

omega = 2 * np.pi * f

# Impedancia del capacitor
Zc = 1.0 / (1j * omega * C)

# NTC en paralelo con capacitor
Zpar = (R_ntc * Zc) / (R_ntc + Zc)

# Inductor
ZL = 1j * omega * L

# Impedancia total del sensor
Zsensor = R_cable + ZL + Zpar

# ============================================================
# 7. SALIDA TEÓRICA DEL PUENTE
# ============================================================

# Nodo A:
# VA = Vin * R2/(R1+R2) = Vin/2

# Nodo B:
# VB = Vin * Zsensor/(R3+Zsensor)

# Vout = VA - VB
relacion_Vout = (
    0.5
    - Zsensor / (R3 + Zsensor)
)

Vout_teorico = (
    Vin_pico_estimado
    * relacion_Vout
)

Vout_pico_teorico = np.abs(Vout_teorico)
Vout_pp_teorico = 2 * Vout_pico_teorico

fase_teorica = np.angle(
    Vout_teorico,
    deg=True
)

# ============================================================
# 8. ERROR EXPERIMENTAL
# ============================================================

error_amplitud = (
    abs(Vout_pico_exp - Vout_pico_teorico)
    / Vout_pico_teorico
    * 100
)

# ============================================================
# 9. MOSTRAR RESULTADOS
# ============================================================

print("==============================================")
print("      DATOS EXPERIMENTALES DEL CSV")
print("==============================================")

print(f"CH1 / VA Vpp:              {VA_pp:.4f} V")
print(f"CH2 / VB Vpp:              {VB_pp:.4f} V")
print(f"Vin estimado Vpp:          {Vin_pp_estimado:.4f} V")

print()
print(f"Vout experimental Vpp:     {Vout_pp_exp:.4f} V")
print(f"Vout experimental pico:    {Vout_pico_exp:.4f} V")

print()
print(f"Desfase CH1-CH2:            {fase_AB:.2f} grados")
print(f"Delta t CH1-CH2:           {delta_t_AB*1e6:.3f} us")

print()

print("==============================================")
print("           MODELO TEÓRICO")
print("==============================================")

print(f"Temperatura:                {T_celsius:.1f} °C")
print(f"R_NTC:                      {R_ntc:.2f} ohm")
print(f"R_cable equivalente:        {R_cable:.2f} ohm")
print(f"L:                          {L*1e6:.2f} uH")
print(f"C:                          {C*1e9:.2f} nF")

print()

print(f"|Zsensor|:                  {abs(Zsensor):.2f} ohm")
print(f"Fase Zsensor:               {np.angle(Zsensor, deg=True):.2f} grados")

print()

print(f"Vout teórico pico:          {Vout_pico_teorico:.4f} V")
print(f"Vout teórico Vpp:           {Vout_pp_teorico:.4f} V")
print(f"Fase teórica Vout:          {fase_teorica:.2f} grados")

print()

print("==============================================")
print("              COMPARACIÓN")
print("==============================================")

print(f"Vout pico experimental:     {Vout_pico_exp:.4f} V")
print(f"Vout pico teórico:          {Vout_pico_teorico:.4f} V")
print(f"Error de amplitud:          {error_amplitud:.2f} %")

print()
print("NOTA:")
print("La normalización solo se usa para comparar la forma")
print("y el desfase de CH1 y CH2.")
print("NO modifica los voltajes experimentales del CSV.")

# ============================================================
# 10. GRÁFICA 1: DATOS ORIGINALES
# ============================================================

plt.figure(figsize=(12, 5))

plt.plot(
    t * 1e6,
    VA,
    label="CH1 = Nodo A"
)

plt.plot(
    t * 1e6,
    VB,
    label="CH2 = Nodo B"
)

plt.plot(
    t * 1e6,
    Vout_exp,
    label="Vout experimental = VA - VB"
)

plt.xlabel("Tiempo (us)")
plt.ylabel("Voltaje (V)")
plt.title("Datos experimentales no originales")
plt.grid()
plt.legend()

plt.xlim(0, 500)

plt.show()

# ============================================================
# 11. GRÁFICA 2: CH1 Y CH2 NORMALIZADOS
# ============================================================

plt.figure(figsize=(12, 5))

plt.plot(
    t * 1e6,
    VA_norm,
    label="CH1 normalizado"
)

plt.plot(
    t * 1e6,
    VB_norm,
    label="CH2 normalizado"
)

plt.xlabel("Tiempo (us)")
plt.ylabel("Amplitud normalizada")
plt.title("Comparación de forma y fase CH1 vs CH2")
plt.grid()
plt.legend()

plt.xlim(0, 500)

plt.show()

from google.colab import files
import numpy as np
import matplotlib.pyplot as plt

uploaded = files.upload()

archivo = list(uploaded.keys())[0]

print("Archivo cargado:", archivo)

datos = np.loadtxt(
    archivo,
    delimiter=",",
    skiprows=6
)

CH1 = datos[:, 0] / 1000.0
CH2 = datos[:, 1] / 1000.0

print("CH1 Vpp =", np.ptp(CH1), "V")
print("CH2 Vpp =", np.ptp(CH2), "V")